[package]
name = "hasher"
version = "1.10.1"
edition = "2021"

[dependencies]
base64ct = { version = "1.6.0", features = ["alloc"] }
faccess = "0.2.4"
md-5 = "0.10.6"
rustc-serialize = "0.3.25"
sha1 = "0.10.6"
sha2 = "0.10.8"
